# Generated by Django 5.2.3 on 2025-07-22 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingredient_created_at'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory.ingredient'),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilograms'), ('TN', 'Tonnes')], default='TN', max_length=2),
        ),
    ]
