# Generated by Django 5.2.3 on 2025-07-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_formulaingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionbatch',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilograms'), ('TONNE', 'Tonnes')], default='TONNE', max_length=5),
        ),
    ]
