# Generated by Django 5.2.3 on 2025-08-03 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_ingredient_added_stock_and_more'),
        ('production', '0004_alter_productionbatch_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient'),
        ),
    ]
