# Generated by Django 5.2.3 on 2025-08-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('inventory', 'Inventory Manager'), ('production', 'Production Manager')], default='inventory', max_length=10),
        ),
    ]
