# Generated by Django 5.2.3 on 2025-08-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role_issue',
            field=models.BooleanField(default=False),
        ),
    ]
