# Generated by Django 5.2.3 on 2025-07-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='initial_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
