# Generated by Django 5.2.3 on 2025-07-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_ingredient_initial_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='initial_stock',
            new_name='previous_stock',
        ),
    ]
