# Generated by Django 5.2.3 on 2025-08-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_initial_stock_ingredient_previous_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='added_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='min_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('t', 'Tonnes')], default='kg', max_length=2),
        ),
    ]
